### ISSUE TITLE
authrocket-node authentication error

### ISSUE THREAD

**Issue by heiytor** [authrocket/authrocket-js#7]
Hi, i'm new here and i trying to connect my digitalocean function with the auth-rocket. I follow this [doc guide](https://authrocket.com/docs/sdks/node), and pasted my credentials from my integration tab. But i get an error, heres my code: 

```javascript
const { AuthRocket } = require('@authrocket/authrocket-node');

const authrocket = new AuthRocket({
  apiKey: 'TBD',
  url: myURL,
  realm: myIdRealm,
  loginrocketUrl: myURL,
  jwtKey: myJwt,
});

const main = async (args) => {
  const orgs = await authrocket.orgs.all();

  return { body: orgs };
};

module.exports.main = main;
```

I get this error:

```json
{
"message":"Access denied; check your API credentials and permissions"
"name":"Error"
"stack":"Error: Access denied; check your API credentials and permissions at handleError (/tmp/JHbenGHT/node_modules/@authrocket/authrocket-node/lib/authrocket.js:164:17) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async NodeActionRunner.main [as userScriptMain] (/tmp/JHbenGHT/index.js:12:16)"
}
```

Also, the require alerts this:
![image](https://user-images.githubusercontent.com/107213601/208257210-4d89dde1-f2fa-4185-bc40-7e95bb250f4d.png)

I've tried it on my local machine as well, but the same errors happen. Digitalocean uses HTTPS and my local machine uses HTTP, is this because I don't have an API KEY?

**Comment by zarqman** [comment]
@heiytor, calling `authrocket.orgs.all()` does require an API key. If you don't have one, you may obtain it from the AuthRocket portal. If your current plan doesn't include API access, contact our support team for a trial account of a plan that does. The key will start with `ks_`.

If you already have an API key, then it might not be getting through. Most often it's best to remove `apiKey` from the constructor above and set it using the environment variable `AUTHROCKET_API_KEY`. That definitely works locally and it appears that DigitalOcean Functions support environment variables as well. Alternatively, it can be set directly (as above)--just be sure to secure the key properly (ie: don't commit it to your code).

Lastly, regarding the final message, authrocket-node does not presently include typescript definitions, hence the warning.

**Comment by heiytor** [comment]
@zarqman, thanks for the answer and sorry for the question, I go through the documentation too fast and I don't see this is required. For now, I'm going to buy a plan that has the API key.

About the global environment: yes, DigitalOcean supports them, I don't use them in this code because it's just for testing purposes, but I will use them in the future.

Thanks again for that, and the Auth Rocket documentation is perfect.
